import { useState } from "react"
import { Loader2, Wand2 } from "lucide-react"
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { useAutoGenerate } from "@/hooks/battle"

type Format = "single" | "double"

type Props = {
  open: boolean
  onOpenChange: (open: boolean) => void
  tournamentId: string
  teamsCount: number
  existingCount: number
  onDone: () => void
}

const nextPow2 = (n: number) => {
  let size = 2
  while (size < n) size *= 2
  return size
}

const FORMATS: { value: Format; title: string; text: string }[] = [
  { value: "single", title: "Eliminación simple", text: "Quien pierde queda fuera." },
  { value: "double", title: "Doble eliminación", text: "Quien pierde pasa al bracket de perdedores y tiene otra oportunidad." },
]

function AutoGenerateDialog({ open, onOpenChange, tournamentId, teamsCount, existingCount, onDone }: Props) {
  const [format, setFormat] = useState<Format>("single")
  const { mutateAsync, isPending } = useAutoGenerate()

  const size = nextPow2(Math.max(teamsCount, 2))
  const versus = format === "single" ? size - 1 : size >= 4 ? 2 * size - 2 : size - 1
  const byes = size - teamsCount
  const tooFew = teamsCount < 2

  const submit = () =>
    mutateAsync({ tournamentId, format, replace: existingCount > 0 })
      .then(() => {
        onOpenChange(false)
        onDone()
      })
      .catch(() => undefined)

  return (
    <AlertDialog open={open} onOpenChange={onOpenChange}>
      <AlertDialogContent className="max-w-lg border-admin-border bg-admin-surface p-0">
        <AlertDialogHeader className="border-b border-admin-border px-6 py-4">
          <AlertDialogTitle className="flex items-center gap-2 text-xl text-admin-text">
            <Wand2 className="h-5 w-5 text-admin-muted" /> Autogenerar bracket
          </AlertDialogTitle>
          <AlertDialogDescription className="text-admin-muted">
            Crea todos los versus con sus conexiones ya ordenados. Después puedes mover y ajustar lo que quieras.
          </AlertDialogDescription>
        </AlertDialogHeader>

        <div className="space-y-4 p-6">
          <div role="radiogroup" aria-label="Formato" className="grid gap-3">
            {FORMATS.map((item) => (
              <button
                key={item.value}
                type="button"
                role="radio"
                aria-checked={format === item.value}
                onClick={() => setFormat(item.value)}
                className={`rounded-lg border p-3 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-admin-accent ${
                  format === item.value
                    ? "border-admin-accent bg-admin-accent/10"
                    : "border-admin-border hover:bg-white/5"
                }`}
              >
                <p className="font-medium text-admin-text">{item.title}</p>
                <p className="text-sm text-admin-muted">{item.text}</p>
              </button>
            ))}
          </div>

          <div className="rounded-lg border border-admin-border bg-admin-input p-3 text-sm text-admin-text">
            {tooFew ? (
              <p className="text-amber-300">Se necesitan al menos 2 equipos activos.</p>
            ) : (
              <p>
                Con <strong>{teamsCount}</strong> equipos se crearán <strong>{versus}</strong> versus
                {byes > 0 && ` (${byes} equipo${byes > 1 ? "s pasan" : " pasa"} directo a la siguiente ronda)`}.
              </p>
            )}
            {format === "double" && byes > 0 && (
              <p className="mt-2 text-xs text-amber-300">
                En doble eliminación con equipos libres, algún hueco del bracket de perdedores puede quedar vacío; edítalo a mano si hace falta.
              </p>
            )}
          </div>

          {existingCount > 0 && (
            <p className="rounded-lg border border-red-500/40 bg-red-500/10 p-3 text-sm text-red-300">
              Ya hay {existingCount} versus en este torneo. Si continúas, se reemplazarán.
            </p>
          )}
        </div>

        <div className="flex justify-end gap-3 border-t border-admin-border px-6 py-4">
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
            className="border-admin-border bg-transparent text-admin-text hover:bg-admin-input"
          >
            Cancelar
          </Button>
          <Button
            type="button"
            onClick={submit}
            disabled={isPending || tooFew}
            className="bg-admin-accent text-white hover:bg-admin-accent-hover"
          >
            {isPending ? (
              <span className="flex items-center gap-2">
                <Loader2 className="h-4 w-4 animate-spin" /> Generando...
              </span>
            ) : existingCount > 0 ? (
              "Reemplazar y generar"
            ) : (
              "Generar"
            )}
          </Button>
        </div>
      </AlertDialogContent>
    </AlertDialog>
  )
}

export default AutoGenerateDialog
