import "@xyflow/react/dist/style.css";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Background,
  BackgroundVariant,
  Controls,
  MiniMap,
  Panel,
  ReactFlow,
  ReactFlowProvider,
  useNodesState,
  useReactFlow,
  type Connection,
  type Edge,
  type NodeMouseHandler,
} from "@xyflow/react";
import { useIsMutating } from "@tanstack/react-query";
import {
  AlertTriangle,
  Check,
  CircleHelp,
  Copy,
  Link2Off,
  Loader2,
  Maximize,
  Pencil,
  Redo2,
  Trash2,
  Undo2,
  Wand2,
  Workflow,
} from "lucide-react";
import {
  isBattleSlot,
  isLinkKind,
  type BattleSlot,
  type LinkKind,
  type TBattle,
} from "@/app/api/battle/battle.types";
import {
  useBattles,
  useCreateBattle,
  useDeleteBattle,
  useLinkBattle,
  useMigrateBattles,
  useMoveBattles,
  useUpdateBattle,
} from "@/hooks/battle";
import { useTeamsByTournament } from "@/hooks/team";
import { CustomToast } from "@/lib/handleToast";
import { Button } from "@/components/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import CreateBattleModal from "@/components/modals/CreateBattleModal";
import UpdateBattleDialog from "@/components/modals/UpdateBattleDialog";
import { BracketContext, type BracketContextValue } from "./BracketContext";
import {
  ROW_H,
  autoLayout,
  computeWarnings,
  createsCycle,
  incomingOf,
  needsLayout,
  toEdges,
  toNodes,
  type VersusNode as VersusNodeType,
} from "./bracketGraph";
import VersusNode from "./VersusNode";
import TeamPalette from "./TeamPalette";
import AutoGenerateDialog from "./AutoGenerateDialog";
import BracketHelp from "./BracketHelp";
import BracketShare from "./BracketShare";
import { useBracketHistory } from "./useBracketHistory";
import type { Team } from "@/app/api/team/team.types";

const nodeTypes = { versus: VersusNode };
const NO_BATTLES: TBattle[] = [];
const NO_TEAMS: Team[] = [];
const NODE_W = 288;

type MenuState = { id: string; x: number; y: number } | null;

type Props = {
  tournamentId: string;
  readOnly?: boolean;
  className?: string;
};

function Canvas({ tournamentId, readOnly = false, className = "" }: Props) {
  const { data: battles = NO_BATTLES, isLoading } = useBattles(tournamentId);
  const { data: teams = NO_TEAMS } = useTeamsByTournament(
    readOnly ? undefined : tournamentId,
  );
  const rf = useReactFlow();
  const wrapper = useRef<HTMLDivElement>(null);
  const fitted = useRef(false);
  const dragStart = useRef(new Map<string, { x: number; y: number }>());

  const [nodes, setNodes, onNodesChange] = useNodesState<VersusNodeType>([]);
  const [menu, setMenu] = useState<MenuState>(null);
  const [editing, setEditing] = useState<TBattle | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [generateOpen, setGenerateOpen] = useState(false);
  const [helpOpen, setHelpOpen] = useState(false);
  const [selectedTeam, setSelectedTeam] = useState<string | null>(null);

  const move = useMoveBattles();
  const link = useLinkBattle();
  const update = useUpdateBattle();
  const create = useCreateBattle();
  const remove = useDeleteBattle();
  const migrate = useMigrateBattles();
  const history = useBracketHistory();
  const saving = useIsMutating() > 0;

  const unorganized = needsLayout(battles);
  const showAutoLayout = readOnly && unorganized;
  const warnings = useMemo(() => computeWarnings(battles), [battles]);
  const edges = useMemo(() => toEdges(battles), [battles]);
  const decided = battles.filter((battle) => battle.winner).length;

  const fitSoon = useCallback(
    () =>
      setTimeout(
        () => rf.fitView({ padding: 0.2, duration: 300, maxZoom: 1 }),
        80,
      ),
    [rf],
  );

  // El servidor es la fuente de verdad: los nodos se rehacen cuando cambian los versus.
  useEffect(() => {
    const base = toNodes(battles);
    const forced = showAutoLayout
      ? new Map(autoLayout(battles).map((p) => [p.id, p]))
      : null;
    setNodes((previous) => {
      const selected = new Set(
        previous.filter((node) => node.selected).map((node) => node.id),
      );
      return base.map((node) => {
        const position = forced?.get(node.id);
        return {
          ...node,
          position: position ? { x: position.x, y: position.y } : node.position,
          selected: selected.has(node.id),
        };
      });
    });
  }, [battles, showAutoLayout, setNodes]);

  useEffect(() => {
    if (fitted.current || nodes.length === 0) return;
    fitted.current = true;
    fitSoon();
  }, [nodes.length, fitSoon]);

  // Deshacer / rehacer con el teclado
  useEffect(() => {
    if (readOnly) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (
        event.target instanceof HTMLElement &&
        event.target.closest(
          "input, textarea, [role='dialog'], [contenteditable]",
        )
      )
        return;
      if (!(event.ctrlKey || event.metaKey)) return;
      const key = event.key.toLowerCase();
      if (key === "z") {
        event.preventDefault();
        if (event.shiftKey) history.redo();
        else history.undo();
      } else if (key === "y") {
        event.preventDefault();
        history.redo();
      }
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [readOnly, history.undo, history.redo]);

  const getCenter = () => {
    const rect = wrapper.current?.getBoundingClientRect();
    const point = rf.screenToFlowPosition({
      x: (rect?.left ?? 0) + (rect?.width ?? 600) / 2,
      y: (rect?.top ?? 0) + (rect?.height ?? 400) / 2,
    });
    return { x: Math.round(point.x - NODE_W / 2), y: Math.round(point.y - 60) };
  };

  // --- Mover ---------------------------------------------------------------
  const saveMoves = (
    before: { id: string; x: number; y: number }[],
    after: { id: string; x: number; y: number }[],
  ) => {
    move.mutate(after);
    history.push({
      label: "Mover",
      undo: () => move.mutateAsync(before),
      redo: () => move.mutateAsync(after),
    });
  };

  const onNodeDragStart = (
    _event: unknown,
    _node: unknown,
    dragged: VersusNodeType[],
  ) => {
    dragStart.current = new Map(
      dragged.map((node) => [node.id, { ...node.position }]),
    );
  };

  const onNodeDragStop = (
    _event: unknown,
    _node: unknown,
    dragged: VersusNodeType[],
  ) => {
    const before: { id: string; x: number; y: number }[] = [];
    const after: { id: string; x: number; y: number }[] = [];
    for (const node of dragged) {
      const start = dragStart.current.get(node.id);
      const x = Math.round(node.position.x);
      const y = Math.round(node.position.y);
      if (!start || (Math.round(start.x) === x && Math.round(start.y) === y))
        continue;
      before.push({
        id: node.id,
        x: Math.round(start.x),
        y: Math.round(start.y),
      });
      after.push({ id: node.id, x, y });
    }
    if (after.length) saveMoves(before, after);
  };

  const arrange = () => {
    const after = autoLayout(battles).map(({ id, x, y }) => ({
      id,
      x: Math.round(x),
      y: Math.round(y),
    }));
    const before = battles.map((battle) => ({
      id: battle._id,
      x: battle.position?.x ?? 0,
      y: battle.position?.y ?? 0,
    }));
    saveMoves(before, after);
    fitSoon();
  };

  // --- Conectar ------------------------------------------------------------
  const setLink = (
    id: string,
    kind: LinkKind,
    target: string | null,
    slot?: BattleSlot,
  ) => link.mutateAsync({ id, kind, target, slot });

  const previousLink = (id: string, kind: LinkKind) => {
    const battle = battles.find((item) => item._id === id);
    return kind === "winner" ? battle?.winnerTo : battle?.loserTo;
  };

  const onConnect = (connection: Connection) => {
    const { source, target, sourceHandle, targetHandle } = connection;
    if (
      !source ||
      !target ||
      !isLinkKind(sourceHandle) ||
      !isBattleSlot(targetHandle)
    )
      return;
    const kind = sourceHandle;
    const slot = targetHandle;
    const previous = previousLink(source, kind);

    setLink(source, kind, target, slot)
      .then(() =>
        history.push({
          label: "Conectar",
          undo: () =>
            setLink(source, kind, previous?.battle ?? null, previous?.slot),
          redo: () => setLink(source, kind, target, slot),
        }),
      )
      .catch(() => undefined);
  };

  const isValidConnection = (connection: Connection | Edge) => {
    const { source, target, targetHandle } = connection;
    if (!source || !target || source === target) return false;
    if (!isBattleSlot(targetHandle)) return false;
    if (incomingOf(battles).get(target)?.[targetHandle]) return false;
    return !createsCycle(battles, source, target);
  };

  const onEdgesDelete = (deleted: Edge[]) => {
    for (const edge of deleted) {
      const kind = edge.id.split(":")[1];
      if (!isLinkKind(kind)) continue;
      const previous = previousLink(edge.source, kind);
      if (!previous) continue;
      setLink(edge.source, kind, null)
        .then(() =>
          history.push({
            label: "Quitar conexión",
            undo: () =>
              setLink(edge.source, kind, previous.battle, previous.slot),
            redo: () => setLink(edge.source, kind, null),
          }),
        )
        .catch(() => undefined);
    }
  };

  // --- Asignar equipos ------------------------------------------------------
  const assignTeam = (battleId: string, slot: BattleSlot, teamId: string) => {
    const battle = battles.find((item) => item._id === battleId);
    if (!battle) return;
    const otherSlot = slot === "teamOne" ? "teamTwo" : "teamOne";
    if (battle[otherSlot]?._id === teamId) {
      CustomToast.warning("Ese equipo ya está en el otro lado del versus");
      return;
    }
    const previous = battle[slot]?._id ?? "";
    const apply = (value: string) =>
      update.mutateAsync({ id: battleId, [slot]: value });

    apply(teamId)
      .then(() => {
        setSelectedTeam(null);
        history.push({
          label: "Asignar equipo",
          undo: () => apply(previous),
          redo: () => apply(teamId),
        });
      })
      .catch(() => undefined);
  };

  // --- Menú contextual -------------------------------------------------------
  const onNodeContextMenu: NodeMouseHandler = (event, node) => {
    if (readOnly) return;
    event.preventDefault();
    const rect = wrapper.current?.getBoundingClientRect();
    setMenu({
      id: node.id,
      x: event.clientX - (rect?.left ?? 0),
      y: event.clientY - (rect?.top ?? 0),
    });
  };

  const menuBattle = menu
    ? battles.find((battle) => battle._id === menu.id)
    : undefined;

  const duplicate = (battle: TBattle) =>
    create
      .mutateAsync({
        tournament: tournamentId,
        date: battle.date,
        position: {
          x: Math.round(battle.position.x + 40),
          y: Math.round(battle.position.y + ROW_H),
        },
      })
      .then(() =>
        CustomToast.success("Versus duplicado (sin equipos ni conexiones)"),
      )
      .catch(() => undefined);

  const disconnectAll = async (battle: TBattle) => {
    const jobs: Promise<unknown>[] = [];
    if (battle.winnerTo) jobs.push(setLink(battle._id, "winner", null));
    if (battle.loserTo) jobs.push(setLink(battle._id, "loser", null));
    for (const other of battles) {
      if (other.winnerTo?.battle === battle._id)
        jobs.push(setLink(other._id, "winner", null));
      if (other.loserTo?.battle === battle._id)
        jobs.push(setLink(other._id, "loser", null));
    }
    await Promise.all(jobs).catch(() => undefined);
  };

  const focusBattle = (id: string) => {
    setNodes((current) =>
      current.map((node) => ({ ...node, selected: node.id === id })),
    );
    rf.fitView({ nodes: [{ id }], padding: 0.6, duration: 400, maxZoom: 1 });
  };

  const context = useMemo<BracketContextValue>(
    () => ({ readOnly, selectedTeam, assignTeam, editBattle: setEditing }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [readOnly, selectedTeam, battles],
  );

  const empty = !isLoading && battles.length === 0;

  return (
    <BracketContext.Provider value={context}>
      <div
        ref={wrapper}
        className={`relative h-full min-h-[480px] w-full overflow-hidden rounded-lg border border-admin-border bg-admin-bg ${className}`}
      >
        <ReactFlow
          nodes={nodes}
          edges={edges}
          nodeTypes={nodeTypes}
          onNodesChange={onNodesChange}
          onConnect={onConnect}
          onEdgesDelete={onEdgesDelete}
          onBeforeDelete={async ({ edges: toDelete }) => ({
            nodes: [],
            edges: toDelete,
          })}
          isValidConnection={isValidConnection}
          onNodeDragStart={onNodeDragStart}
          onNodeDragStop={onNodeDragStop}
          onNodeContextMenu={onNodeContextMenu}
          onPaneClick={() => setMenu(null)}
          onMoveStart={() => setMenu(null)}
          colorMode="dark"
          snapToGrid
          snapGrid={[20, 20]}
          minZoom={0.1}
          maxZoom={1.5}
          nodesDraggable={!readOnly}
          nodesConnectable={!readOnly}
          elementsSelectable={!readOnly}
          edgesFocusable={!readOnly}
          zoomOnScroll={!readOnly}
          preventScrolling={!readOnly}
          zoomOnDoubleClick={false}
          deleteKeyCode={readOnly ? null : ["Backspace", "Delete"]}
        >
          <Background
            variant={BackgroundVariant.Dots}
            gap={20}
            size={1}
            color="#2c2c3a"
          />
          <Controls showInteractive={false} />
          <MiniMap
            pannable
            zoomable
            className="!bg-admin-surface"
            maskColor="rgba(0,0,0,0.5)"
            nodeColor="#7c3aed"
          />

          <Panel position="top-left" className="!m-3">
            <div className="flex flex-wrap items-center gap-2 rounded-lg border border-admin-border bg-admin-surface/95 p-2 shadow-lg backdrop-blur">
              {!readOnly && (
                <>
                  <CreateBattleModal compact getPosition={getCenter} />
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setGenerateOpen(true)}
                    className="border-admin-border bg-transparent text-admin-text hover:bg-white/5"
                  >
                    <Wand2 className="mr-2 h-4 w-4" /> Autogenerar
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={arrange}
                    disabled={battles.length === 0}
                    title="Ordena los versus por capas según sus conexiones"
                    className="border-admin-border bg-transparent text-admin-text hover:bg-white/5"
                  >
                    <Workflow className="mr-2 h-4 w-4" /> Ordenar
                  </Button>
                  <span className="mx-1 h-6 w-px bg-admin-border" />
                  <Button
                    type="button"
                    size="icon"
                    variant="ghost"
                    onClick={history.undo}
                    disabled={!history.canUndo}
                    aria-label="Deshacer (Ctrl+Z)"
                    title="Deshacer (Ctrl+Z)"
                    className="text-admin-text hover:bg-white/5"
                  >
                    <Undo2 className="h-4 w-4" />
                  </Button>
                  <Button
                    type="button"
                    size="icon"
                    variant="ghost"
                    onClick={history.redo}
                    disabled={!history.canRedo}
                    aria-label="Rehacer (Ctrl+Y)"
                    title="Rehacer (Ctrl+Y)"
                    className="text-admin-text hover:bg-white/5"
                  >
                    <Redo2 className="h-4 w-4" />
                  </Button>
                </>
              )}
              <Button
                type="button"
                size="icon"
                variant="ghost"
                onClick={() =>
                  rf.fitView({ padding: 0.2, duration: 300, maxZoom: 1 })
                }
                aria-label="Encuadrar todo"
                title="Encuadrar todo"
                className="text-admin-text hover:bg-white/5"
              >
                <Maximize className="h-4 w-4" />
              </Button>
              <BracketShare
                tournamentId={tournamentId}
                disabled={battles.length === 0}
              />

              {battles.length > 0 && (
                <div
                  className="flex items-center gap-2 px-1 text-sm text-admin-muted"
                  role="status"
                >
                  <div className="h-2 w-24 overflow-hidden rounded-full bg-white/10">
                    <div
                      className="h-full bg-green-500 transition-all"
                      style={{
                        width: `${Math.round((decided / battles.length) * 100)}%`,
                      }}
                    />
                  </div>
                  <span>
                    {decided}/{battles.length} resueltos
                  </span>
                </div>
              )}

              {!readOnly && (
                <>
                  {warnings.length > 0 && (
                    <Popover>
                      <PopoverTrigger asChild>
                        <Button
                          type="button"
                          variant="ghost"
                          className="gap-1.5 px-2 text-amber-300 hover:bg-amber-500/10 hover:text-amber-200"
                        >
                          <AlertTriangle className="h-4 w-4" />{" "}
                          {warnings.length}
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent className="w-80 border-admin-border bg-admin-surface p-2 text-admin-text">
                        <p className="px-2 py-1 text-xs text-admin-muted">
                          Haz clic para ir al versus
                        </p>
                        <ul className="max-h-64 overflow-y-auto">
                          {warnings.map((warning, index) => (
                            <li key={`${warning.battleId}-${index}`}>
                              <button
                                type="button"
                                onClick={() => focusBattle(warning.battleId)}
                                className="w-full rounded-md px-2 py-1.5 text-left text-sm hover:bg-white/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-admin-accent"
                              >
                                {warning.message}
                              </button>
                            </li>
                          ))}
                        </ul>
                      </PopoverContent>
                    </Popover>
                  )}
                  <span
                    className="flex items-center gap-1.5 px-1 text-xs text-admin-muted"
                    role="status"
                    aria-live="polite"
                  >
                    {saving || move.isPending ? (
                      <>
                        <Loader2 className="h-3.5 w-3.5 animate-spin" />{" "}
                        Guardando...
                      </>
                    ) : (
                      <>
                        <Check className="h-3.5 w-3.5 text-green-400" />{" "}
                        Guardado
                      </>
                    )}
                  </span>
                  <Button
                    type="button"
                    size="icon"
                    variant="ghost"
                    onClick={() => setHelpOpen((value) => !value)}
                    aria-label="Cómo usar el bracket"
                    aria-expanded={helpOpen}
                    className="text-admin-text hover:bg-white/5"
                  >
                    <CircleHelp className="h-4 w-4" />
                  </Button>
                </>
              )}
            </div>
          </Panel>

          {!readOnly && (
            <Panel position="top-right" className="!m-3">
              <TeamPalette
                teams={teams}
                battles={battles}
                selected={selectedTeam}
                onSelect={setSelectedTeam}
              />
            </Panel>
          )}

          {!readOnly &&
            (helpOpen ||
              (!isLoading &&
                battles.length > 0 &&
                !localStorage.getItem("bracket-help-seen"))) && (
              <Panel position="bottom-center" className="!mb-3">
                <BracketHelp
                  onClose={() => {
                    localStorage.setItem("bracket-help-seen", "1");
                    setHelpOpen(false);
                  }}
                />
              </Panel>
            )}

          {!readOnly && unorganized && (
            <Panel position="top-center" className="!mt-24">
              <div className="flex items-center gap-3 rounded-lg border border-amber-500/40 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">
                Estos versus aún no tienen posición ni conexiones.
                <Button
                  type="button"
                  size="sm"
                  disabled={migrate.isPending}
                  onClick={() =>
                    migrate
                      .mutateAsync(tournamentId)
                      .then(() => fitSoon())
                      .catch(() => undefined)
                  }
                  className="bg-admin-accent text-white hover:bg-admin-accent-hover"
                >
                  {migrate.isPending
                    ? "Organizando..."
                    : "Organizar automáticamente"}
                </Button>
              </div>
            </Panel>
          )}
        </ReactFlow>

        {isLoading && (
          <div className="pointer-events-none absolute inset-0 flex items-center justify-center text-admin-muted">
            <Loader2 className="mr-2 h-5 w-5 animate-spin" /> Cargando
            bracket...
          </div>
        )}

        {empty && (
          <div className="pointer-events-none absolute inset-0 flex items-center justify-center p-4">
            <div className="pointer-events-auto max-w-sm rounded-lg border border-dashed border-admin-border bg-admin-surface/95 p-6 text-center">
              <p className="font-medium text-admin-text">
                {readOnly
                  ? "El bracket aún no está disponible"
                  : "Aún no hay versus"}
              </p>
              {!readOnly && (
                <>
                  <p className="mt-1 text-sm text-admin-muted">
                    Genera el bracket completo con tus equipos o crea los versus
                    uno por uno.
                  </p>
                  <Button
                    type="button"
                    onClick={() => setGenerateOpen(true)}
                    className="mt-4 bg-admin-accent text-white hover:bg-admin-accent-hover"
                  >
                    <Wand2 className="mr-2 h-4 w-4" /> Autogenerar bracket
                  </Button>
                </>
              )}
            </div>
          </div>
        )}

        {menu && menuBattle && (
          <div
            role="menu"
            style={{ left: menu.x, top: menu.y }}
            className="absolute z-50 w-52 rounded-md border border-admin-border bg-admin-surface p-1 text-sm text-admin-text shadow-xl"
          >
            {[
              {
                label: "Editar",
                icon: Pencil,
                run: () => setEditing(menuBattle),
              },
              {
                label: "Duplicar",
                icon: Copy,
                run: () => duplicate(menuBattle),
              },
              {
                label: "Quitar conexiones",
                icon: Link2Off,
                run: () => disconnectAll(menuBattle),
              },
              {
                label: "Eliminar",
                icon: Trash2,
                run: () => setDeleting(menuBattle._id),
                danger: true,
              },
            ].map(({ label, icon: Icon, run, danger }) => (
              <button
                key={label}
                type="button"
                role="menuitem"
                onClick={() => {
                  setMenu(null);
                  run();
                }}
                className={`flex w-full items-center gap-2 rounded px-2 py-1.5 text-left hover:bg-white/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-admin-accent ${
                  danger ? "text-red-400" : ""
                }`}
              >
                <Icon className="h-4 w-4" /> {label}
              </button>
            ))}
          </div>
        )}
      </div>

      {!readOnly && (
        <>
          {editing && (
            <UpdateBattleDialog
              battle={editing}
              isOpen
              onClose={() => setEditing(null)}
            />
          )}

          <AutoGenerateDialog
            open={generateOpen}
            onOpenChange={setGenerateOpen}
            tournamentId={tournamentId}
            teamsCount={
              teams.filter((team) => team.status !== "inactive").length
            }
            existingCount={battles.length}
            onDone={() => {
              history.clear();
              fitSoon();
            }}
          />

          <AlertDialog
            open={!!deleting}
            onOpenChange={(open) => !open && setDeleting(null)}
          >
            <AlertDialogContent className="border-admin-border bg-admin-surface">
              <AlertDialogHeader>
                <AlertDialogTitle className="text-admin-text">
                  Eliminar versus
                </AlertDialogTitle>
                <AlertDialogDescription className="text-admin-muted">
                  Se quitarán también sus conexiones y los huecos que alimentaba
                  quedarán vacíos. Esta acción no se puede deshacer.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel className="border-admin-border bg-transparent text-admin-text hover:bg-white/5">
                  Cancelar
                </AlertDialogCancel>
                <AlertDialogAction
                  onClick={() => {
                    const id = deleting;
                    setDeleting(null);
                    if (id) remove.mutate(id);
                  }}
                  className="bg-red-600 text-white hover:bg-red-700"
                >
                  Eliminar
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </>
      )}
    </BracketContext.Provider>
  );
}

function BracketCanvas(props: Props) {
  return (
    <ReactFlowProvider>
      <Canvas {...props} />
    </ReactFlowProvider>
  );
}

export default BracketCanvas;
